---
title: "final project"
author: "Lizbet Ortiz"
date: "2023-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(purrr)
library(rvest)
library(lubridate)
library(tidyverse)
library(ggplot2)
library(dplyr)

# Get data from local cvs file (data was downloaded from https://www.deq.louisiana.gov/page/eric-public-reports)
data_set_before_2015 <- read_excel("Annual_Certified_Emissions_before_2015.xlsx") 
data_set_after_2015 <- read_excel("Annual_Certified_Emissions_after_2015.xlsx")
#View(dataset)
```

```{r}

# Select pollutants/variables that contribute the most to cancer
data_set_before_2015 <- data_set_before_2015 %>% 
  select(REPORTING_YEAR,
        AI_NAME, 
        PARISH_OR_COUNTY_DESC,
        `1,3-Butadiene`,
        `Arsenic (and compounds)`,
        `Asbestos`,
        `Benzene`,
        `Benzidine`,
        `Beryllium (Table 51.1)`,
        `Cadmium (and compounds)`,
        `Chromium VI (and compounds)`,
        `Ethylene oxide`,
        `Formaldehyde`,
        `Nickel (and compounds)`,
        `Nickel (refinery dust)`,
        `Sulfuric acid`,
        `Trichloroethylene`,
        `Vinyl chloride`
        )

# Select pollutants/variables that contribute the most to cancer
data_set_after_2015 <- data_set_after_2015 %>% 
  select(REPORTING_YEAR,
        AI_NAME, 
        PARISH_OR_COUNTY_DESC,
        `1,3-Butadiene`,
        `Arsenic (and compounds)`,
        `Asbestos`,
        `Benzene`,
        `Benzidine`,
        `Beryllium (Table 51.1)`,
        `Cadmium (and compounds)`,
        `Chromium VI (and compounds)`,
        `Ethylene oxide`,
        `Formaldehyde`,
        `Nickel (and compounds)`,
        `Nickel (refinery dust)`,
        `Sulfuric acid`,
        `Trichloroethylene`,
        `Vinyl chloride`
        )
```


```{r}
# Join both tables to have a single data set
data_set <- data_set_before_2015 %>% 
  full_join(data_set_after_2015, 
            by = join_by(REPORTING_YEAR,
                        AI_NAME, 
                        PARISH_OR_COUNTY_DESC,
                        `1,3-Butadiene`,
                        `Arsenic (and compounds)`,
                        `Asbestos`,
                        `Benzene`,
                        `Benzidine`,
                        `Beryllium (Table 51.1)`,
                        `Cadmium (and compounds)`,
                        `Chromium VI (and compounds)`,
                        `Ethylene oxide`,
                        `Formaldehyde`,
                        `Nickel (and compounds)`,
                        `Nickel (refinery dust)`,
                        `Sulfuric acid`,
                        `Trichloroethylene`,
                        `Vinyl chloride`)) %>% 
  arrange(AI_NAME)
```


```{r}
# Creating `ascension` table and filter data based on `Ascension` county
ascension <- data_set %>% 
  filter(PARISH_OR_COUNTY_DESC == "Ascension") %>% 
  arrange(AI_NAME)

# Creating `calcasieu` table and filter data based on `Calcasieu` county
calcasieu <- data_set %>% 
  filter(PARISH_OR_COUNTY_DESC == "Calcasieu") %>% 
  arrange(AI_NAME)
```

```{r}
# Selecting facilities that contributed to the production of at least one pollutant
ascension2 <- ascension %>% filter(rowSums(is.na(ascension)) != ncol(ascension) - 3)
calcasieu2 <- calcasieu %>% filter(rowSums(is.na(calcasieu)) != ncol(calcasieu) - 3)


# Replace NA values with 0
ascension2[is.na(ascension2)] <- 0
calcasieu2[is.na(calcasieu2)] <- 0
```

```{r}

# Calculate the mean of the column mycolumn in mydata
mean_Butadiene <- mean(ascension2$`1,3-Butadiene`)

# Generate a summary of the mean of mycolumn
summary_mean_Butadiene<- summary(mean_Butadiene)

# View the summary
summary_mean_Butadiene

```

```{r}
#calculated the mean for each pollutant in ascension county from 2000 to 2018

mean_ascension <- ascension2 %>%
  # only show years from 2000 to 2018
  filter(REPORTING_YEAR >= 2000 & REPORTING_YEAR <= 2018) %>%
  group_by(REPORTING_YEAR) %>%
  summarise(total_butadiene = mean(`1,3-Butadiene`), 
            total_arsenic = mean(`Arsenic (and compounds)`),
            total_asbestos = mean(Asbestos),
            total_benzene = mean(Benzene),
            total_benzidine = mean(Benzidine),
            total_beryllium = mean(`Beryllium (Table 51.1)`),
            total_cadmium = mean(`Cadmium (and compounds)`),
            total_chromium = mean(`Chromium VI (and compounds)`),
            total_ethylene = mean(`Ethylene oxide`),
            total_formaldehyde = mean(Formaldehyde),
            total_nickelc = mean(`Nickel (and compounds)`),
            total_nickeld = mean(`Nickel (refinery dust)`),
            total_sulfuric = mean(Trichloroethylene),
            total_vinyl = mean(`Vinyl chloride`)) %>% 
 
   pivot_longer(cols = 2:15,
               names_to = "pollutant",
               values_to = "total") %>% 
 filter(`total` != 0)  # Filter out rows where total is 0
  
mean_ascension %>%  
  ggplot(aes(x = factor(REPORTING_YEAR), y = total, fill = pollutant)) +
  geom_bar(stat = "identity") +
  labs(title = "Prevalence of Mean Pollutant Concentration (2000-2018)",
       x = "Year",
       y = "Mean Concentration") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```
```{r}
#calculated the mean for each pollutant in calcasieu county from 2000 to 2018

mean_calcasieu <- calcasieu2 %>%
  # only show years from 2000 to 2018
  filter(REPORTING_YEAR >= 2000 & REPORTING_YEAR <= 2018) %>%
  group_by(REPORTING_YEAR) %>%
  summarise(total_butadiene = mean(`1,3-Butadiene`),
            total_arsenic = mean(`Arsenic (and compounds)`),
            total_asbestos = mean(Asbestos),
            total_benzene = mean(Benzene),
            total_benzidine = mean(Benzidine),
            total_beryllium = mean(`Beryllium (Table 51.1)`),
            total_cadmium = mean(`Cadmium (and compounds)`),
            total_chromium = mean(`Chromium VI (and compounds)`),
            total_ethylene = mean(`Ethylene oxide`),
            total_formaldehyde = mean(Formaldehyde),
            total_nickelc = mean(`Nickel (and compounds)`),
            total_nickeld = mean(`Nickel (refinery dust)`),
            total_sulfuric = mean(Trichloroethylene),
            total_vinyl = mean(`Vinyl chloride`)) %>% 
 
   pivot_longer(cols = 2:15,
               names_to = "pollutant",
               values_to = "total") %>% 
 filter(`total` != 0)  # Filter out rows where total is 0
  
mean_calcasieu %>%  
  ggplot(aes(x = factor(REPORTING_YEAR), y = total, fill = pollutant)) +
  geom_bar(stat = "identity") +
  labs(title = "Prevalence of Mean Pollutant Concentration (2000-2018)",
       x = "Year",
       y = "Mean Concentration") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```


```{r}
ascension2 %>% 
  ggplot(aes(x = REPORTING_YEAR, y = mean_concentration, fill = pollutant)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Prevalence of Mean Pollutant Concentration (2000-2018)",
       x = "Year",
       y = "Mean Concentration")

```


```{r}
ascension_facilities <- ascension %>% 
  group_by(REPORTING_YEAR) %>% 
  summarise(total = n()) 
  
```












```{r}
# Creating a new table that holds the total number of facilities in each county and the total number of facilities that contributed to any of the selected pollutants

facilities_by_county <- tibble(county = c("Ascension", 
                                          "Calcasieu"),
                               total_facilities = c(nrow(ascension %>% 
                                                           group_by(AI_NAME, 
                                                                    REPORTING_YEAR) %>% 
                                                           summarise(total = n())), 
                                                    nrow(calcasieu %>%
                                                           group_by(AI_NAME, 
                                                                    REPORTING_YEAR) %>% 
                                                           summarise(total = n()))),
                               pollutant_facilities = c(nrow(ascension2 %>% 
                                                           group_by(AI_NAME, 
                                                                    REPORTING_YEAR) %>% 
                                                           summarise(total = n())), 
                                                        nrow(calcasieu2 %>%
                                                               group_by(AI_NAME, 
                                                                        REPORTING_YEAR) %>% 
                                                               summarise(total = n()))))
```


```{r}
facilities_by_county2 <- facilities_by_county %>% 
  pivot_longer(cols=2:3, 
               names_to = "names", 
               values_to = "count")


ggplot(facilities_by_county2, aes(x = factor(county), 
                                  y = count,  
                                  fill = names, 
                                  colour = names)) + 
  geom_bar(stat = "identity") + 
  labs(title = "Total number of facilities by county & pollutant facilities",
       y = "County",
       x = "Total") +
  theme_bw()

```


























```{r}
testing_ascension <- ascension %>% 
  anti_join(ascension2, 
            by = join_by(REPORTING_YEAR,
                        AI_NAME, 
                        PARISH_OR_COUNTY_DESC,
                        `1,3-Butadiene`,
                        `Arsenic (and compounds)`,
                        `Asbestos`,
                        `Benzene`,
                        `Benzidine`,
                        `Beryllium (Table 51.1)`,
                        `Cadmium (and compounds)`,
                        `Chromium VI (and compounds)`,
                        `Ethylene oxide`,
                        `Formaldehyde`,
                        `Nickel (and compounds)`,
                        `Nickel (refinery dust)`,
                        `Sulfuric acid`,
                        `Trichloroethylene`,
                        `Vinyl chloride`)) %>% 
  arrange(AI_NAME)

testing_calcasieu <- calcasieu %>% 
  anti_join(calcasieu2, 
            by = join_by(REPORTING_YEAR,
                        AI_NAME, 
                        PARISH_OR_COUNTY_DESC,
                        `1,3-Butadiene`,
                        `Arsenic (and compounds)`,
                        `Asbestos`,
                        `Benzene`,
                        `Benzidine`,
                        `Beryllium (Table 51.1)`,
                        `Cadmium (and compounds)`,
                        `Chromium VI (and compounds)`,
                        `Ethylene oxide`,
                        `Formaldehyde`,
                        `Nickel (and compounds)`,
                        `Nickel (refinery dust)`,
                        `Sulfuric acid`,
                        `Trichloroethylene`,
                        `Vinyl chloride`)) %>% 
  arrange(AI_NAME)
```

